version: '3.8'

services:
  customer-app:
    build:
      context: ./customer-front-thymeleaf-app
    image: customer-app:latest
    container_name: customer-app
    environment:
      VAULT_TOKEN: myroot
      VAULT_ADDR: http://185.97.144.204:8200
    ports:
      - "8075:8075"
    depends_on:
      - my-loki
      - my-tempo
    networks:
      - vault_network

  inventory-service:
    build:
      context: ./inventory-service
    image: inventory-service:latest
    container_name: inventory-service
    environment:
      VAULT_TOKEN: myroot
      VAULT_ADDR: http://185.97.144.204:8200
    ports:
      - "8098:8098"
    networks:
      - vault_network

  cadivosr:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
    ports:
      - "8070:8080"

  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /var/jenkins_home/workspace/Spring-Microservice/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  ## Tempo
  my-tempo:
    image: grafana/tempo
    container_name: my-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # zipkin
  my-loki:
    image: grafana/loki:main
    container_name: my-loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
networks:
  vault_network:
    external: true